# Generated by Django 4.1.3 on 2022-11-05 09:10

from django.db import migrations, models
import django.db.models.deletion
import store.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Nom complet')),
                ('slug', models.SlugField(blank=True, max_length=150)),
            ],
            options={
                'verbose_name': 'Auteur',
            },
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name="Maison d'édition")),
                ('slug', models.SlugField(blank=True, max_length=150)),
            ],
            options={
                'verbose_name': 'Editeur',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Titre')),
                ('slug', models.SlugField(blank=True, max_length=150)),
                ('isbn', models.CharField(blank=True, max_length=17, null=True, unique=True, validators=[store.validators.validate_isbn], verbose_name='N° ISBN')),
                ('resume', models.TextField(blank=True, verbose_name='Résumé')),
                ('pages', models.IntegerField(default=0, verbose_name='Nombre de pages')),
                ('publication_date', models.DateField(blank=True, null=True, verbose_name='Paru le')),
                ('price', models.FloatField(default=0.0, verbose_name='Prix')),
                ('quantity', models.IntegerField(default=0, verbose_name='Quantité')),
                ('author', models.ForeignKey(default='Inconnu', on_delete=django.db.models.deletion.SET_DEFAULT, to='store.author', verbose_name='Auteur')),
                ('publisher', models.ForeignKey(default='Inconnu', on_delete=django.db.models.deletion.SET_DEFAULT, to='store.publisher', verbose_name="Maison d'édition")),
            ],
            options={
                'verbose_name': 'Livre',
            },
        ),
    ]
