# Generated by Django 4.1.3 on 2022-11-05 12:35

from django.db import migrations, models
import store.models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_book_author_alter_book_publisher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ForeignKey(null=True, on_delete=models.SET(store.models.get_default_author), to='store.author', verbose_name='Auteur'),
        ),
        migrations.AlterField(
            model_name='book',
            name='publisher',
            field=models.ForeignKey(null=True, on_delete=models.SET(store.models.get_default_publisher), to='store.publisher', verbose_name="Maison d'édition"),
        ),
    ]
